HASRestaurant/Areas/Admin/Controllers/AdminReservationController.cs
using HASRestaurant.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HASRestaurant.Areas.Admin.Controllers
{
    public class AdminReservationController : Controller
    {
        PRN292_HAS_RestaurantEntities objModel = new PRN292_HAS_RestaurantEntities();
        // GET: Admin/AdminReservation
        public ActionResult Index()
        {
            var lstRes = objModel.Reservations.ToList();
            return View(lstRes);
        }
        public ActionResult Details(int? id)
        {
            var lstRes = objModel.Reservations.Where(n => n.ReservationID == id).FirstOrDefault();
            return View(lstRes);
        }
    }
}

HASRestaurant/Controllers/DetailController.cs
using HASRestaurant.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HASRestaurant.Controllers
{
    public class DetailController : Controller
    {
        PRN292_HAS_RestaurantEntities objModel = new PRN292_HAS_RestaurantEntities();
        // GET: Detail
        public ActionResult Index(int? Id)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var objProduct = objModel.Products.Where(n => n.ProductID == Id).FirstOrDefault();
            return View(objProduct);
        }
    }
}

HASRestaurant/Areas/Admin/Views/AdminReservation/Details.cshtml
@model HASRestaurant.Context.Reservation

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .listright {
        margin-left: 273px;
    }
</style>
<div class="listright">

    <h2>Details</h2>

    <div>
        <h4>Reservation</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CustomerName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.NumOfGuests)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NumOfGuests)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReservationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Message)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Message)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>

HASRestaurant/Areas/Admin/Views/AdminReservation/Index.cshtml
@model IEnumerable<HASRestaurant.Context.Reservation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    .listright {
        margin-left: 273px;
    }

        .listright h2 {
            margin-bottom: 20px;
        }

    td img {
        width: 60px;
        height: 60px;
    }

    .listright p a {
        color: #ffffff;
        background-color: #fb5849;
        padding: 10px;
    }

        .listright p a:hover {
            background-color: #ff0000;
            color: #ffffff;
        }

    .listright td a:hover {
        color: #ff0000;
    }
</style>

<div class="listright">
    <h2>Manager Reservation</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.NumOfGuests)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.ReservationDate)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Time)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(ModelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(ModelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(ModelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(ModelItem => item.NumOfGuests)
                </td>
                <td>
                    @Html.DisplayFor(ModelItem => item.ReservationDate)
                </td>
                <td>
                    @Html.DisplayFor(ModelItem => item.Time)
                </td>
                <td>
                    <a href="@Url.Action("Details","AdminReservation", new { id = item.ReservationID})" class="fas fa-file-alt"></a>
                </td>
            </tr>

        }
    </table>
</div>