HASRestaurant/Controllers/CartController.cs
using HASRestaurant.Context;
using HASRestaurant.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HASRestaurant.Controllers
{
    public class CartController : Controller
    {
        PRN292_HAS_RestaurantEntities db = new PRN292_HAS_RestaurantEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult OrderNow(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Product p = db.Products.Find(id);
            if (p.Quantity != 0)
            {
                if (Session["cart"] == null)
                {
                    List<CartModel> lstCart = new List<CartModel>
                {
                    new CartModel(db.Products.Find(id),1)
                };
                    Session["cart"] = lstCart;
                }
                else
                {
                    List<CartModel> lstCart = (List<CartModel>)Session["cart"];
                    int checkExist = isExistCheck(id);
                    if (checkExist == -1)
                    {
                        if (isValidProduct(id) != -1)
                        {
                            lstCart.Add(new CartModel(db.Products.Find(id), 1));
                        }
                    }
                    else
                    {
                        if (lstCart[checkExist].Quantity < db.Products.Find(id).Quantity)
                        {
                            lstCart[checkExist].Quantity++;
                        }
                    }
                    Session["cart"] = lstCart;
                }
                return View("Index");
            }
            else
            {
                TempData["mess"] = "Product Out Stock!!!";
                return RedirectToAction("Index","Menu");
            }
        }
        private int isExistCheck(int? id)
        {
            List<CartModel> lstCart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < lstCart.Count; i++)
            {
                if (lstCart[i].Product.ProductID == id) return i;
            }
            return -1;
        }
        private int isValidProduct(int? id)
        {
            var lstAllProduct = db.Products.ToList();
            for (int i = 0; i < lstAllProduct.Count; i++)
            {
                if (lstAllProduct[i].ProductID == id) return lstAllProduct[i].ProductID;
            }
            return -1;
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            int check = isExistCheck(id);
            List<CartModel> lstCart = (List<CartModel>)Session["cart"];
            if (check != -1)
            {
                lstCart.RemoveAt(check);
            }
            Session["cart"] = lstCart;
            return View("Index");
        }
        public ActionResult AddQuantity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            int check = isExistCheck(id);
            List<CartModel> lstCart = (List<CartModel>)Session["cart"];
            if (check != -1)
            {
                if (lstCart[check].Quantity < db.Products.Find(id).Quantity)
                {
                    lstCart[check].Quantity++;
                }
            }
            Session["cart"] = lstCart;
            return View("Index");
        }
        public ActionResult SubQuantity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            int check = isExistCheck(id);
            List<CartModel> lstCart = (List<CartModel>)Session["cart"];
            if (check != -1)
            {
                if (lstCart[check].Quantity > 1)
                {
                    lstCart[check].Quantity--;
                }
            }
            Session["cart"] = lstCart;
            return View("Index");
        }
    }
}

HASRestaurant/Controllers/CheckOutController.cs
using HASRestaurant.Context;
using HASRestaurant.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace HASRestaurant.Controllers
{
    public class CheckOutController : Controller
    {
        PRN292_HAS_RestaurantEntities objModel = new PRN292_HAS_RestaurantEntities();
        // GET: CheckOut
        public ActionResult Index()
        {
            if (Session["user"] != null)
            {
                Order od = new Order();
                od.Email = ((Account)Session["user"]).Email;
                return View(od);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        //FormCollection frc
        [HttpPost]
        public ActionResult CheckOut(Order order)
        {
            if (Session["user"] != null)
            {
                if (ModelState.IsValid)
                {
                    //1.Save order into Order table
                    List<CartModel> lstCart = (List<CartModel>)Session["cart"];
                    Account acc = (Account)Session["user"];
                    order.UserID = acc.UserID;
                    order.TotalPrice = lstCart.Sum(x => x.Quantity * x.Product.Price);
                    order.OrderDate = DateTime.Now;
                    objModel.Orders.Add(order);
                    objModel.SaveChanges();
                    //2.Save order detail
                    string subcontent = "";
                    foreach (CartModel item in lstCart)
                    {
                        OrderDetail orderDetail = new OrderDetail()
                        {
                            OrderID = order.OrderID,
                            ProductID = item.Product.ProductID,
                            Quantity = item.Quantity,
                            UnitPrice = item.Quantity * item.Product.Price
                        };
                        subcontent += "<tr><td>" +item.Product.ProductName+"</td><td>"+item.Quantity+"</td><td>"+ (item.Quantity * item.Product.Price)+"</td></tr>";
                        objModel.OrderDetails.Add(orderDetail);
                        objModel.SaveChanges();
                    }
                    //3. Send Mail
                    MailMessage mm = new MailMessage("dohuy776@gmail.com", order.Email);
                    mm.Subject = "[HAS Restaurant - Confirm: Order successfully!!!]";
                    string contentMail = "<h1>Hello: " + order.CustomerName + ". You have successfully placed an order from HAS Restaurant</h1>";
                    contentMail += "<hr/><dl><dd>Customer Name: " + order.CustomerName + "</dd>";
                    contentMail += "<dd>Total Price: " + order.TotalPrice + "</dd>";
                    contentMail += "<dd>Order Date: " + order.OrderDate + "</dd>";
                    contentMail += "<dd>Phone: " + order.Phone + "</dd>";
                    contentMail += "<dd>Address: " + order.Address + "</dd>";
                    contentMail += "<dd>Note: " + order.Note + "</dd>";
                    contentMail += "<dd>Email: " + order.Email + "</dd>";
                    contentMail += "</dl>";
                    contentMail += "<table class='table' border='1'><tr><th>Product Name</th><th>Quantity</th><th>Unit Price</th></tr>";
                    contentMail += subcontent;
                    contentMail += "</table>";
                    string linkContact = "Click here to <a href='http://localhost:62452/Menu/Index'>shopping now!</a>";
                    mm.Body = String.Format(contentMail + linkContact);
                    mm.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    NetworkCredential nc = new NetworkCredential();
                    nc.UserName = "dohuy776@gmail.com";
                    nc.Password = "he140044..";
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = nc;
                    smtp.Port = 587;
                    smtp.Send(mm);

                    //4.Update quantity
                    foreach (CartModel item in lstCart)
                    {
                        Product product = objModel.Products.SingleOrDefault(b => b.ProductID == item.Product.ProductID);
                        product.Quantity -= item.Quantity;
                        objModel.Entry(product).State = EntityState.Modified;
                        objModel.SaveChanges();
                    }
                    //5.Remove session
                    Session.Remove("cart");
                    return RedirectToAction("Index", "OrderHistory");
                }
                /*if (ModelState.IsValid)
                {
                    //1.Save order into Order table
                    List<CartModel> lstCart = (List<CartModel>)Session["cart"];
                    Account acc = (Account)Session["user"];
                    Order order = new Order()
                    {
                        UserID = acc.UserID,
                        CustomerName = frc["firstname"],
                        TotalPrice = lstCart.Sum(x => x.Quantity * x.Product.Price),
                        OrderDate = DateTime.Now,
                        Phone = frc["phone"],
                        Address = frc["address"],
                        Note = frc["note"],
                        Email = frc["email"]
                    };
                    objModel.Orders.Add(order);
                    objModel.SaveChanges();
                    //2.Save order detail
                    foreach (CartModel item in lstCart)
                    {
                        OrderDetail orderDetail = new OrderDetail()
                        {
                            OrderID = order.OrderID,
                            ProductID = item.Product.ProductID,
                            Quantity = item.Quantity,
                            UnitPrice = item.Quantity * item.Product.Price
                        };
                        objModel.OrderDetails.Add(orderDetail);
                        objModel.SaveChanges();
                    }
                    //3.Remove session
                    Session.Remove("cart");
                    return View("Index");
                }
                return View("Index");*/
                return View("Index", order);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

HASRestaurant/Views/Cart/Index.cshtml
@using HASRestaurant.Models;
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/css/font-awesome.css">
<link rel="stylesheet" href="~/Content/assets/css/templatemo-klassy-cafe.css">
<link rel="stylesheet" href="~/Content/assets/css/owl-carousel.css">
<link rel="stylesheet" href="~/Content/assets/css/lightbox.css">
<link rel="stylesheet" href="~/Content/assets/css/cart.css">

@{
    if (Session["cart"] != null && ((List<CartModel>)Session["cart"]).Count > 0)
    {
        <!-- ***** Header Area End ***** -->
        <div class="cart">
            <section class="section" id="mycart">

                <div class="cart-table-area section-padding-100">
                    <div class="container-fluid">
                        <div class="cart-title mt-50">
                            <h2>My Cart</h2>
                        </div>
                        <div class="row">
                            <div class="col-12 col-lg-8">
                                <div class="cart-table clearfix">
                                    <table class="table table-responsive">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Name</th>
                                                <th>Price</th>
                                                <th>Quantity</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in (List<CartModel>)Session["cart"])
                                            {
                                                <tr>
                                                    <td class="cart_product_img">
                                                        <a href="#"><img src="@item.Product.Image" alt="Product"></a>
                                                    </td>
                                                    <td class="cart_product_desc">
                                                        <h6>@item.Product.ProductName</h6>
                                                    </td>
                                                    <td class="price">
                                                        <span>$@item.Product.Price</span>
                                                    </td>
                                                    <td class="qty">
                                                        <a href="@Url.Action("SubQuantity", "Cart", new { id = item.Product.ProductID})" style="color: #f86c5f;"><button class="btnSub">-</button></a>
                                                        <strong>@item.Quantity</strong>
                                                        <a href="@Url.Action("AddQuantity", "Cart", new { id = item.Product.ProductID})" style="color: #f86c5f;"><button class="btnAdd">+</button></a>
                                                        <a href="@Url.Action("Delete", "Cart", new { id = item.Product.ProductID })">
                                                            <i class="glyphicon glyphicon-trash" style="color:#f86c5f; margin-left: 180px;"></i>
                                                        </a>
                                                    </td>

                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="cart-summary">
                                    <h5>Cart Total</h5>
                                    <ul class="summary-table">
                                        @{
                                            List<CartModel> temp = (List<CartModel>)Session["cart"];
                                            var total = temp.Sum(x => x.Quantity * x.Product.Price);
                                        }
                                        <li class=""><span>Subtotal:</span> <span class="price"></span></li>
                                        @foreach (var item in (List<CartModel>)Session["cart"])
                                        {
                                            <li class=""><span>@item.Product.ProductName</span> <span class="price">$@(item.Product.Price * item.Quantity)</span></li>
                                        }
                                        <li><span>Delivery:</span> <span>Free</span></li>
                                        <li><span>Total:</span> <span>$@total</span></li>
                                    </ul>
                                    <div class="cart-btn mt-100">
                                        <a href="@Url.Action("Index","CheckOut")" class="btn amado-btn w-100">Checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div> }
    else
    {
        <div class="cart">
            <section class="section" id="mycart">

                <div class="cart-table-area section-padding-100">
                    <div class="container-fluid">
                        <div class="cart-title mt-50">
                            <h2>My Cart</h2>
                        </div>
                        <div class="row">
                            <div class="col-12 col-lg-8">
                                <div class="cart-table clearfix">
                                    <table class="table table-responsive">
                                        <br/>
                                        <br/>
                                        <h1>No item in your cart!!!</h1>
                                    </table>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="cart-summary">
                                    <h5>Cart Total</h5>
                                    <ul class="summary-table">
                                        <li class=""><span>Subtotal:</span> <span class="price"></span></li>
                                        <li><span>Delivery:</span> <span>Free</span></li>
                                        <li><span>Total:</span> <span>$0</span></li>
                                    </ul>
                                    <div class="cart-btn mt-100">
                                        <a href="#" class="btn amado-btn w-100" onclick="alert('Please order something!')">Checkout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div>
    }
}